### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by ABadi42** [kevalmorabia97/CoVA-Web-Object-Detection#6]
Hi,

First of all, thanks for sharing your work. As a student in last year of engineering school, I try to create a project to find object from webpage screenshots.

I made some tests with Tensorflow and Pytorch. Some were more or less efficient at this point of my work...

I tried to run your project, and have some questions if you don't mind :

- Training worked as expected. Do you know if it is possible to follow training with tensorboard ?
- After training a model, I wanted to test it, but wasn't able to do so. I ran `python extract_attn_wts_and_visualize.py 1` but it gave me an error : `FileNotFoundError: [Errno 2] No such file or directory: 'results_5-Fold_CV/lr-5e-04 batch-5 cs-12 hd-384 roi-3 bbhd-32 af-0 wd-1e-03 dp-0.2 sf-0.9/Fold-1 saved_model.pth'`. I would like to run generated model on an image, and eventually visualize result in an image, or at least get bounding boxes. Could you point me in right direction ?
- If I understand correctly, you made your own model. But I saw that `resnet18-f37072fd.pth` was used. Does this mean that you start from a pre trained model, and then apply yours ?

Sorry if I am not clear enough, I just started ML a few days ago...

Thank you !

**Comment by kevalmorabia97** [comment]
Thanks for using our code!
Regarding your questions:
* You can update the code to use tensorboard by adding the write statements when the metrics are computed and printed e.g. in the `train.py` file
* For getting attention visualizations, can you take a look at the parameters in the file and make sure you used those parameters? When you trained your model, it would print where the results are stored. Check if it is same as `results_5-Fold_CV/lr-5e-04 batch-5 cs-12 hd-384 roi-3 bbhd-32 af-0 wd-1e-03 dp-0.2 sf-0.9/...`
* Yes, we start with a pre-trained resnet-18 model. We keep the first 5 layers from pretrained resnet18 and add the additional layers like Positional Encoder, Graph Attention Network and FC layers and then everything is trained end-to-end. You can find model details in https://arxiv.org/abs/2110.12320

**Comment by ABadi42** [comment]
Thanks !

Regarding Tensorboard, I will try it !

I finally achieve testing a dataset. I think there is a bug somewhere, but not sure, what I exactly did :
- Training `python main.py -bs 2 -e 1 -cvf 1`
- Evaluating `python extract_attn_wts_and_visualize.py 1`

This worked but I had to "force" value to `params = 'lr-5e-04 batch-2 cs-12 hd-384 roi-3 bbhd-32 af-0 wd-1e-03 dp-0.2 sf-0.9'` in `extract_attn_wts_and_visualize.py`

**Comment by kevalmorabia97** [comment]
Yes, the `extract_attn_wts_and_visualize.py` had parameters hard coded
